env:
  browser: true
  commonjs: true
  es2021: true
  jest/globals: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
plugins: 
  - jest
  - fp
rules: {
  max-classes-per-file: ["error", 3],
  fp/no-mutation: ["off", {
    "commonjs": true,
    "allowThis": true}]
}
